import ScaleRoundedIcon from '@mui/icons-material/ScaleRounded';
import FlightRoundedIcon from '@mui/icons-material/FlightRounded';
import FlightTakeoffRoundedIcon from '@mui/icons-material/FlightTakeoffRounded';
import WifiTetheringRoundedIcon from '@mui/icons-material/WifiTetheringRounded';
import SpeedRoundedIcon from '@mui/icons-material/SpeedRounded';
import AccessTimeRoundedIcon from '@mui/icons-material/AccessTimeRounded';
import React from 'react';

const listParameters = [
  {
    type: 'TextInput',
    isRequired: true,
    isMultiline: false,
    name: '_name',
    label: 'Назва',
    placeholder: 'Назва БПЛА...',
  },
  {
    type: 'TextInput',
    isRequired: true,
    isMultiline: false,
    name: 'model',
    label: 'Модель',
    placeholder: 'Модель БПЛА...',
  },
  {
    type: 'TextInput',
    isRequired: false,
    isMultiline: true,
    name: 'shortDescription',
    label: 'Короткий опис',
    placeholder: 'Короткий опис БПЛА...',
  },
  {
    type: 'TextInput',
    isRequired: false,
    isMultiline: true,
    name: 'description',
    label: 'Детальний опис загальньої інформації',
    placeholder: 'Опис...',
  },
  {
    type: 'TextInput',
    isRequired: false,
    isMultiline: false,
    name: 'vendor',
    label: 'Виробник',
    placeholder: 'Виробник БПЛА...',
  },
  {
    type: 'SelectInput',
    title: 'Країна виробник',
    name: 'contryVendor',
    label: 'Країна',
    variants: [
      'Україна',
      'Австралія',
      'Австрія',
      'Азербайджан',
      'Аргентина',
      'Білорусь',
      'Бельгія',
      'Болгарія',
      'Бразилія',
      'Велика Британія',
      'Вірменія',
      'Ізраїль',
      'Індія',
      'Іран',
      'Італія',
      'Іспанія',
      'Казахстан',
      'Канада',
      'Китай',
      'Німеччина',
      'Норвегія',
      "Об'єднані Арабські Емірати",
      'Польща',
      'Південно-Африканська Республіка',
      'США',
      'Туреччина',
      'Франція',
      'Чехія',
      'Швейцарія',
    ],
  },
  {
    type: 'SelectInput',
    title: 'Тип двигуна',
    name: 'typeEngine',
    label: 'Тип',
    variants: ['Електричний', 'Дізельний', 'Бензиновий'],
  },
  {
    type: 'MultipleSelect',
    title: 'Функії',
    name: 'functions',
    label: 'Функції',
    variants: [
      'Розвідка',
      'Цілевказання',
      'Відновлення та ретрансляція зв’язку',
      'Підсвічування в темний час',
      'Радіаційна, хімічна та біологічна розвідки',
      'Виявлення мін',
      'Пошук і рятування',
      'Гасіння пожеж',
      'Транспортування вантажів',
      'Протидія аматорським БпЛА',
    ],
  },
  {
    type: 'MultipleSelect',
    title: 'Рівень застосування',
    name: 'levelsApply',
    label: 'Рівень',
    variants: ['ТВД', 'Оперативна група', 'Бригада', 'Батальйон', 'Рота', 'Взвод', 'Відділення'],
  },
  {
    type: 'SelectInput',
    title: 'Рівень воєнних дій',
    name: 'levelWarActions',
    label: 'Рівень',
    variants: [
      'Cтратегічний',
      'Оперативний',
      'Тактичний',
      'Тактичне формування',
      'Тактичний підрозділ',
    ],
  },
  {
    type: 'SelectInput',
    title: 'Класс',
    name: '_class',
    label: 'Класс',
    variants: [
      'МікроБпЛА',
      'МініБпЛА',
      'БпЛА близької дії',
      'БпЛА малої дальності',
      'БпЛА середньої дальності',
      'Мало-висотні БпЛА глибинної розвідки',
      'БпЛА великої дальності',
      'Середньовисотні БпЛА великої тривалості польоту',
      'Висотні БпЛА великої тривалості польоту',
      'Ударні БпЛА',
    ],
  },
  {
    type: 'NumberSlider',
    title: 'Дальність польоту (км)',
    icon: React.Fragment,
    name: 'flightRange',
    min: 0,
    max: 2000,
    step: 10,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Розмах крил (м)',
    icon: FlightRoundedIcon,
    name: 'wingspan',
    min: 0,
    max: 30,
    step: 1,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Максимальна злітна маса (кг)',
    icon: ScaleRoundedIcon,
    name: 'maxFlyWeight',
    min: 0,
    max: 15000,
    step: 50,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Корисне навантаження (кг)',
    icon: ScaleRoundedIcon,
    name: 'payloadWeight',
    min: 0,
    max: 2000,
    step: 10,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Максимальна швидкість (км/год)',
    icon: SpeedRoundedIcon,
    name: 'maxSpeed',
    min: 0,
    max: 800,
    step: 10,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Крейсерна швидкість (км/год)',
    icon: SpeedRoundedIcon,
    name: 'cruiseSpeed',
    min: 0,
    max: 500,
    step: 10,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Максимальна висота польоту (км)',
    icon: FlightTakeoffRoundedIcon,
    name: 'maxFlyHeight',
    min: 0,
    max: 50,
    step: 1,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Операційна висота використання (км)',
    icon: WifiTetheringRoundedIcon,
    name: 'heightOfUse',
    min: 0,
    max: 50,
    step: 1,
    countMarkBase: 5,
  },
  {
    type: 'NumberSlider',
    title: 'Тривалість польоту (годин)',
    icon: AccessTimeRoundedIcon,
    name: 'flyDuration',
    min: 0,
    max: 75,
    step: 1,
    countMarkBase: 5,
  },
];

export default listParameters;
